use Socket;
use Term::ANSIColor;
use WWW::Mechanize;
use JSON;
print color 'bold bright_yellow';
print color 'reset';
@iphost=$ARGV[0] || die "Usage : ./Iplocation.pl [host] [ip] [domain] \n\nEx:  ./Iplocation.pl  www.google.com \n     ./Iplocation.pl  216.58.210.206\n \n";
my @ip = inet_ntoa(scalar gethostbyname("@iphost")or die "IP or Host invalid!\n");
my @hn = scalar gethostbyaddr(inet_aton(@ip),AF_INET);
my $GET=WWW::Mechanize->new();
    $GET->get("http://ip-api.com/json/@ip"); 
    my $json = $GET->content();
my $info = decode_json($json);
print "  [!] IP: ", $info->{'query'}, "\n";
print "------------------------------------\n"; 
print "  [+] ORG: ", $info->{'as'}, "\n";
print "------------------------------------\n";
print "  [+] ISP: ", $info->{'isp'}, "\n";
print "------------------------------------\n";
print "  [+] Country: ", $info->{'country'}," - ", $info->{'countryCode'}, "\n";
print "------------------------------------\n";
print "  [+] City: ", $info->{'city'}, "\n";
print "------------------------------------\n";
print "  [+] Region: ", $info->{'regionName'}, " - " , $info->{'region'}, "\n";
print "------------------------------------\n";
print "  [+] Geo: ", "Lat: " , $info->{'lat'}, " - Long: ", $info->{'lon'}, "\n";
print "------------------------------------\n";
print "  [+] Time: ", "timezone: " , $info->{'timezone'}, " - Long: ", $info->{'timezone'}, "\n";
print "------------------------------------\n";
print "  [+] ORG: ", $info->{'as'}, "\n";
print "------------------------------------\n";
print "  [+] Country code: ", $info->{'countryCode'}, "\n"; 
print "------------------------------------\n";
print "  [+] Status: ", $info->{'status'}, "\n"; 
print "\n";

